# Generated by Django 2.1.4 on 2019-07-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_drive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='app',
        ),
        migrations.AddField(
            model_name='drive',
            name='company',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
