# Generated by Django 2.1.4 on 2019-07-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190719_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='company',
        ),
        migrations.AddField(
            model_name='drive',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
