# Generated by Django 2.1.4 on 2019-07-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190719_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stu_apply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stu_select',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
