# Generated by Django 2.1.4 on 2019-07-18 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('img', models.FileField(upload_to='media')),
                ('Year_Of_Completion', models.IntegerField()),
                ('Roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Sex', models.CharField(max_length=8)),
                ('DOB', models.DateField()),
                ('Email', models.CharField(max_length=40)),
                ('Contact', models.IntegerField()),
                ('Percentile', models.IntegerField()),
                ('HighSchool', models.IntegerField()),
                ('HighPer', models.IntegerField()),
                ('Intermediate', models.IntegerField()),
                ('InterPer', models.IntegerField()),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Dept')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
