# Generated by Django 2.1.4 on 2019-07-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='d',
        ),
    ]
