# Generated by Django 2.1.4 on 2019-07-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.AddField(
            model_name='student',
            name='d',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Dept'),
            preserve_default=False,
        ),
    ]
