# Generated by Django 2.1.4 on 2019-07-18 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_auto_20190718_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Stu',
        ),
    ]
