# Generated by Django 2.1.4 on 2019-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190718_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stu',
            name='Roll_number',
            field=models.IntegerField(),
        ),
    ]
